### ISSUE TITLE
Cannot perform search

### ISSUE THREAD

**Issue by jaywal1320** [neo4j-examples/movies-javascript-bolt#154]
After running the project as mentioned in the readme file, the project runs but the search does not work because I am getting errors connecting to the neo4j database.

neo4j-web.min.js:1 WebSocket connection to 'wss://demo.neo4jlabs.com:7687/' failed: 

I can access neo4j and the Movies DB at http://localhost:7474/browser/
and using bolt bolt://localhost:7687/neo4j

Thank You!

**Comment by fbiville** [comment]
I'll let @jexp , but demo.neo4jlabs.com is a [Neo4j Sandbox](https://neo4j.com/sandbox/) instance and I don't think they allow WebSocket connections.

**Comment by jexp** [comment]
It's not a sandbox instance, it's a full server.

it offers `bolt+s://` and `neo4j+s://` connections which should also cover websocket.

We should probably change the URL protocol, to `bolt+s://`

**Comment by peihuacher** [comment]
Faced similar issues. Fixed this by editing the file webpack.config.js

devServer: {
    host: '0.0.0.0', // added this line
  },

 plugins: [
    new HtmlWebpackPlugin({template: 'src/assets/index.html'}),
    new Webpack.EnvironmentPlugin({
      'NEO4J_URI': 'neo4j://localhost:11003', // by default this should work
      ....
    })
  ],

Cheers!

**Comment by jexp** [comment]
But that's a local server (running on a non-standard port, the default port is 7687)?

**Comment by fbiville** [comment]
I believe there is currently a certificate issue with `demo.neo4jlabs.com` which prevents any successful TLS handshake by the drivers when connecting to the DB.

**Comment by fbiville** [comment]
The certificate issue has been fixed.
@jaywal1320 can you try running the application again with the default configuration?

**Comment by peihuacher** [comment]
> But that's a local server (running on a non-standard port, the default port is 7687)?
> 
> 

I was using a local server to test it out 😊
