### ISSUE TITLE
Works only with Neo4j 3.0.1 and higher

### ISSUE THREAD

**Issue by aamanlamba** [neo4j-examples/movies-javascript-bolt#2]
I recently tried to run this with Neo4j 2.3.8 and the server refuses to connect with the error message 

> **"WebSocket connection to 'ws://localhost:7687/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED"**

This error is not observed when connecting to Neo4j v 3.0.1 and higher. This should be clarified in the readme for the sample project

**Comment by fbiville** [comment]
Yes, this repository intends to be an example of small application working with _recent_ versions of Neo4j.
I will go ahead and close this.
