### ISSUE TITLE
Websocket uses the wrong port

### ISSUE THREAD

**Issue by dysbulic** [neo4j-examples/movies-javascript-bolt#5]
This program attempts to connect on port `7687`, I'm using the [neo4j.rb rake tasks](https://github.com/neo4jrb/neo4j-rake_tasks) and the daemon listens on `7472`.

I don't know if this is the case for all modern versions of the daemon or not.

**Comment by fbiville** [comment]
I'm not sure I am following. As far as I understand, there is no Websocket involved here, just a regular Bolt connection to the database, which happens indeed [on the default Bolt port](https://github.com/neo4j-examples/movies-javascript-bolt/blob/2e8324c7754cee3a53bc6bce5684892925594033/src/neo4jApi.js#L7), i.e. `7687`.

You can set an explicit port as in:
```javascript
neo4j.driver("bolt://localhost:7472", neo4j.auth.basic("neo4j", "abcde"));
```
And it should work?

**Comment by fbiville** [comment]
Hi @dysbulic, feel free to reopen the issue if you have more questions on this particular issue.
