### ISSUE TITLE
curl error

### ISSUE THREAD

**Issue by tommyyama2020** [neo4j-examples/movies-javascript-bolt#55]
Hi, 

I am sorry for bothering u but how can i fix this? 
"curl http://localhost:8080/movie/The%20Matrix" is resulting like below

![Screen Shot 2020-12-19 at 18 35 48](https://user-images.githubusercontent.com/38548157/102686184-2eba8480-4229-11eb-84a4-ec2cc1e0b185.png)

**Comment by fbiville** [comment]
Hi, this repository is using client-side JavaScript only, there is only the static HTML file with some JavaScript in it. There is no Node.js backend.
