### ISSUE TITLE
Session closed sync

### ISSUE THREAD

**Issue by alexandrusavin** [neo4j-examples/movies-javascript-bolt#6]
Is it a problem that `session.close()` is called synchronously?

AFAIK, it returns a promise which means that you might end up with multiple parallel opened sessions. 

https://github.com/neo4j-examples/movies-javascript-bolt/blob/2e8324c7754cee3a53bc6bce5684892925594033/src/neo4jApi.js#L19

**Comment by fbiville** [comment]
@alexandrusavin thanks for the report.
You are right, there could an error when closing the session if the underlying connections fail to be released for some reason. Error handling could definitely improved here.

**Comment by fbiville** [comment]
Thanks for the fix https://github.com/neo4j-examples/movies-javascript-bolt/commit/3e79246fd9b96022440872df4b7cdcfd1cd3904d!
