### ISSUE TITLE
Neo4jError: Database access is not allowed for user 'movies' ...

### ISSUE THREAD

**Issue by fivian** [neo4j-examples/movies-javascript-bolt#98]
Hi, I've tried the example, the search page is displayed, but get errors in the chome debug console which begin as shown below 
I'm new to neo4j so forgive me if there something obvious I'm missing.
Thanks
Andy

> Database running at neo4j+s://demo.neo4jlabs.com
> app.js:27259 [WDS] Live Reloading enabled.
> localhost/:1 Uncaught (in promise) Neo4jError: Database access is not allowed for user 'movies' with roles [PUBLIC, movies].
> 
>     at http://localhost:8080/neo4j-web.min.js:1:411695
>     at new i (http://localhost:8080/neo4j-web.min.js:1:411775)
>     at _ (http://localhost:8080/neo4j-web.min.js:1:437700)
>     at Object.run (http://localhost:8080/neo4j-web.min.js:1:434694)
>     at u.value (http://localhost:8080/neo4j-web.min.js:1:433032)
>     at http://localhost:8080/app.js:26948:8
>     at a.value (http://localhost:8080/neo4j-web.min.js:1:394973)
>     at a.value (http://localhost:8080/neo4j-web.min.js:1:394740)
>     at http://localhost:8080/neo4j-web.min.js:1:393860
>     at new Promise (<anonymous>)

**Comment by fivian** [comment]
It's probably some related to 'Run the App inside the Webpack Dev Server:'  I'm not sure what this means. :-(
I'm running in visual studio code.

**Comment by fbiville** [comment]
Sorry for the delay @fivian, this should be fixed now.
